# Usar una imagen de Python con Alpine Linux
FROM python:3.11.9-alpine

# Establecer el directorio de trabajo
WORKDIR /saludos

# Copiar el archivo de requisitos y luego instalar dependencias
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto de la aplicación
EXPOSE 5000

# Agregar un argumento y variable de entorno para el puerto por defecto
ARG ARG_DEFAULT_PORT=8000
EXPOSE $ARG_DEFAULT_PORT
ENV DEFAULT_PORT=${ARG_DEFAULT_PORT}


