# Utiliza una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Instala netcat
RUN apt-get update && apt-get install -y netcat

# Copia los archivos requirements.txt y app.py en el contenedor
COPY requirements.txt requirements.txt
COPY app.py app.py
COPY models.py models.py
COPY entrypoint.sh entrypoint.sh

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Da permisos de ejecución al script de entrada
RUN chmod +x entrypoint.sh

# Ejecuta el script de entrada
ENTRYPOINT ["./entrypoint.sh"]
