version: "1.0"
services:
    db:
        image: prueba:latest
        environment:
           - POSTGRES_PASSWORD=123456

    app: 
        build: .
        ports:
            - 5000:5000
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://postgres:123456@db:5432/prueba



